apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-blog-ingress
  namespace: homepage-blog
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd, default-gzip-compress@kubernetescrd
    external-dns.alpha.kubernetes.io/hostname: "@"
    external-dns.alpha.kubernetes.io/ttl: "3600" #optional
    
spec:
  rules:
    - host: thekitty.zone
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage-blog
                port:
                  number: 80
  tls:
    - secretName: thekitty-zone-tls
      hosts:
        - thekitty.zone

